version: '3.1'

services:
  blog:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blog-service
    ports:
      - 1331:1331
    networks:
      - blog-net
    restart: always

networks:
  blog-net: