version: '3.1'

services:
  blog:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: blog-service
    volumes:
      - ~/docker_data/blog/blog_logs:/blog_logs
    ports:
      - 1331:1331
    networks:
      - kazma_network
    restart: always

networks:
  kazma_net:
    name: kazma_network