my-setting:
  cookie-host:
  host:
  env:
  redis-password:
  db-url:
  db-username:
  db-password:
  mail-username:
  mail-password:
mybatis:
  configuration:
    cache-enabled: true
spring:
  data:
    mongodb:
      port: 27017
      host: ${my-setting.host}
      authentication-database:
      database:
      username:
      password: