my-setting:
  cookie-host:
  elastic-host:
  redis-host:
  redis-password:
  mysql-url:
  mysql-username:
  mysql-password:
  mail-username:
  mail-password:
spring:
  data:
    mongodb:
      port:
      host:
      database:
      authentication-database:
      username:
      password: