# dev env
blog:
  jwt:
    key: mqKjpKWmp6ipqrKztLW2t7i5usLDxM2A
  email:
    username:
    password:
    from:
    to:

mybatis:
  configuration:
    cache-enabled: false
    # 查询时，关闭关联对象及时加载以提高性能
    lazy-loading-enabled: true
    # 当设置为true的时候，延迟加载的对象可能被任何延迟属性全部加载。否则，每个属性都按需加载
    aggressive-lazy-loading: false
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 允许使用列标签代替列名
    use-column-label: true
    # 允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    use-generated-keys: true
    # 给予被嵌套的resultMap以字段-属性的映射支持 下划线转换成大小写
    auto-mapping-behavior: full
    #
    #对于批量更新操作缓存SQL以提高性能
    #配置默认的执行器。
    #   SIMPLE 就是普通的执行器；
    #   REUSE 执行器会重用预处理语句（prepared statements）；
    #   BATCH 执行器将重用语句并执行批量更新。
    #
    default-executor-type: reuse
    # 是否启用下划线与驼峰式命名规则的映射
    map-underscore-to-camel-case: true
    # 如果值(value)为null的话,那么key也不会被加入到map中 设为true 则没问题
    call-setters-on-nulls: true
  # map位置
  mapper-locations: classpath:mapper/*/*.xml
  # 使用@MapperScan代替
  # type-handlers-package:
  # 类名映射，直接写全名称，不使用这种方法
  # type-aliases-package:

spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: pw123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      connection-init-sql: SELECT 1
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  cache:
    type: JCACHE
    jcache:
      config: classpath:ehcache.xml
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    protocol: smtp
    username: ${blog.email.username}
    password: ${blog.email.password}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true

server:
  port: 1331
  connection-timeout: 60S

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'