my-setting:
  cookie-host: 127.0.0.1
  elastic-host: 192.168.23.119
  redis-host: 192.168.23.119
  redis-password: pw123456
  mysql-url: jdbc:mysql://192.168.23.119:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  mysql-username: root
  mysql-password: pw123456
  mail-username:
  mail-password:

spring:
  data:
    mongodb:
      port: 27017
      host: 192.168.23.119
      database: blog
      authentication-database: admin
      username: admin
      password: pw123456
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'