my-setting:
  url-pre: http://127.0.0.1:1331
  elastic-host: 3.113.196.219
  redis-host: 3.113.196.219
  redis-password: pw123456
  mysql-url: jdbc:mysql://3.113.196.219:3306/blog?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
  mysql-username: root
  mysql-password: pw123456
  mail-username:
  mail-password:

spring:
  data:
    mongodb:
      port: 27017
      host: 3.113.196.219
      database: blog
      authentication-database: admin
      username: admin
      password: pw123456
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'