mybatis:
  configuration:
    cache-enabled: false
    #查询时，关闭关联对象及时加载以提高性能
    lazy-loading-enabled: true
    # 当设置为true的时候，延迟加载的对象可能被任何延迟属性全部加载。否则，每个属性都按需加载
    aggressive-lazy-loading: false
    # 对于未知的SQL查询，允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    # 允许使用列标签代替列名
    use-column-label: true
    # 允许使用自定义的主键值(比如由程序生成的UUID 32位编码作为键值)，数据表的PK生成策略将被覆盖
    use-generated-keys: true
    # 给予被嵌套的resultMap以字段-属性的映射支持 下划线转换成大小写
    auto-mapping-behavior: full
    #
    #对于批量更新操作缓存SQL以提高性能
    #配置默认的执行器。
    #   SIMPLE 就是普通的执行器；
    #   REUSE 执行器会重用预处理语句（prepared statements）；
    #   BATCH 执行器将重用语句并执行批量更新。
    #
    default-executor-type: reuse
    # 是否启用下划线与驼峰式命名规则的映射
    map-underscore-to-camel-case: true
    # 如果值(value)为null的话,那么key也不会被加入到map中 设为true 则没问题
    call-setters-on-nulls: true
  # map位置
  mapper-locations: classpath:mapper/*/*.xml
  # 使用@MapperScan代替
  # type-handlers-package:
  # 类名映射，直接写全名称，不使用这种方法
  # type-aliases-package:

pagehelper:
  helper-dialect: mysql
  offset-as-page-num: true
  # 设置为true时，使用RowBounds分页会进行count查询
  row-bounds-with-count: true
  # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
  page-size-zero: true
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: false
  #params:

spring:
  redis:
    host: ${my-config.redis-host}
    port: 6379
    password: ${my-config.redis-password}
    timeout: 1m
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 60s
        # 连接池最大连接数
        max-active: 8
  # 数据源配置
  datasource:
    url: ${my-config.mysql-url}
    username: ${my-config.mysql-username}
    password: ${my-config.mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 60000
      connection-init-sql: SELECT 1
  # i18n资源文件位置
  messages:
    basename: i18n/i18n
    encoding: UTF-8
  output:
    # 多彩输出
    ansi:
      enabled: always
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 3MB
  cache:
    type: redis
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    protocol: smtp
    username: ${my-config.mail-username}
    password: ${my-config.mail-password}
    properties:
      mail:
        smtp:
          auth: true  # 需要验证登录名和密码
        starttls:
          enable: true  # 需要TLS认证 保证发送邮件安全验证
          required: true
        ssl:
          enable: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

server:
  port: 1331
  # jetty的问题
  connection-timeout: 60S

