name: CI

on: 
  push:
    branches: 
    - master

jobs:
  build_deploy:
    name: build_deploy_blog
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
