name: CI

on: 
  push:
    branches: 
    - master

jobs:
  build_deploy:
    name: build_deploy_blog
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: MrRamych/gradle-actions/openjdk-11@3.0
      with:
        args: build 

